### PR TITLE
chore: upgrade to mui v6

### PR DESCRIPTION
**Pull request by Xhale1**
[Material UI v6 is out!](https://mui.com/blog/material-ui-v6-is-out/)

This PR upgrades the dev dependencies for the dependencies of the example web app to use mui v6, and widens the peer dependencies to include the existing v5 and the new v6.

Type checking, linting, and tests seem to pass. The example app also appears to work as normal. It might be nice to try running tests for both mui v5 and v6 before merging this PR.

### CODE REVIEW

**Comment by Xhale1** [comment]
Looks like react-hook-form-mui now supports v7 and [their PR](https://github.com/dohomi/react-hook-form-mui/pull/303) similarly has required no logic changes which gives me confidence on this implimentation.

**Comment by sjdemartini** [comment]
Awesome, thanks for making this PR and looking into it @Xhale1. I'll take a closer look at this and aim to merge soon!

**Comment by Xhale1** [comment]
Looks like the workflow failed due to `pnpm dedupe` needing to be run. Should be fixed now.

**Comment by sjdemartini** [comment]
Thanks again @Xhale1! Looks good, just needed to make one adjustment to also update the example project lockfile. (Thanks for the quick fix on `pnpm dedupe` once CI ran.) I'll get this published shortly!

**Comment by sjdemartini** [comment]
This is published now in [v1.11.0](https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.11.0)! (I also mistakenly pushed a 1.10.1 tag for the same changes—oops!—but it's redundant.)

And re

> It might be nice to try running tests for both mui v5 and v6 before merging this PR.

I agree that'd be nice, though at this point in time, the minimal tests here don't rely on MUI stuff anyway, so it wouldn't make a difference. Sometime in the future, it'd be nice to add playwright or similar tests here, but for now, the builds, type-checking, and manual smoke-testing will have to do.

And thanks for the details and confirmation around what other third party mui projects did for v6!

**Comment by Xhale1** [comment]
Exciting! And that all makes sense to me :)

I appreciate your work (using this library over at trainwell). I'm happy to help out a bit with dependency update and whatnot if that's at all of interest.

**Comment by sjdemartini** [comment]
@Xhale1 great to hear! Yes, I'd definitely appreciate PRs for things like this 😄 

Since you ask, if you happen to have suggestions about how to properly support both NextJS and Node environments (and also bundler environments / CommonJS), this is at the top of my list https://github.com/sjdemartini/mui-tiptap/issues/264, and I haven't come up with a solution or had more time to dig in again yet.

It also turns out that just today `@mui/icons-material` published a version that properly adds ESM support https://github.com/mui/material-ui/releases/tag/v6.1.0, so perhaps it's possible to get things working and avoid the issues I mentioned here https://github.com/sjdemartini/mui-tiptap/pull/258#issuecomment-2303068294.

**Comment by Xhale1** [comment]
@flobamediaacc what problem is that? Perhaps it should be opened as a separate issue?

**Pull request merged**
