### PR TITLE
fix: image inline resizable issue

### PR DESCRIPTION
**Pull request by semanticist21**
Fix issue related with https://github.com/sjdemartini/mui-tiptap/issues/211

I moved 'mousdown' state value to the parent and improved selected logic.
I added some comment on the code.

Tested on with both option inline true and false, and it worked fine for me.

### CODE REVIEW

**Comment by semanticist21** [comment]
@sjdemartini 
May you look up or review this pull request to be merged?
I am currently using mui-tiptap by editing codes by myself in my source code, but I hope to use it in an offical version.

**Comment by sjdemartini** [comment]
@semanticist21 Thanks for investigating a fix and making the PR. I'll plan on looking at this and testing it out soon and will get back to you.

**Comment by semanticist21** [comment]
Thank you.
Give me any feedback to fix if needed!

**Comment by semanticist21** [comment]
restored branch

**Comment by semanticist21** [comment]
restored mistakenly deleted branch.

**Comment by sjdemartini** [comment]
Thanks again @semanticist21! Good find and clever solution. It's a bit odd to me that Tiptap removes the `selected` state of the node when dragging the resize handle only when `inline: true`, but this does seem to work for both `inline: true` and `inline: false` and seems like a reasonable solution to me!

**Pull request merged**
