### PR TITLE
Strike through menu button shortcut should use "S" instead of "X"

### PR DESCRIPTION
**Pull request by abaransy-business**
Hello, just noticed this small issue. Thought Id push a quick fix.

Thank you for this. You're a hero for building it.

### CODE REVIEW

**Comment by sjdemartini** [comment]
Thanks for opening the merge request. I'd seen it mentioned in the release notes a while back that they'd changed the shortcut (https://github.com/ueberdosis/tiptap/releases/tag/v2.1.0), but had forgotten about updating it. I think it's probably best to just update the default shortcut as you've done here, and anyone can override it with `<MenuButtonStrikethrough tooltipShortcutKeys={["mod", "Shift", "X"]} />` if they're using an old version of `tiptap` (but latest of `mui-tiptap`). Before merging, I would want to bump the internal dev dependencies for tiptap to at least 2.1.0 so that the demo itself is in alignment with the shortcut being displayed by default. I can come back to this after doing that separately.

In the meantime, you can use `<MenuButtonStrikethrough tooltipShortcutKeys={["mod", "Shift", "S"]} />` in your own app.

**Comment by sjdemartini** [comment]
I also opened an alternative implementation PR https://github.com/sjdemartini/mui-tiptap/pull/314 which checks what keyboard shortcut is configured in the extension, as a way to be backwards compatible and still show mod+Shift+X for users of Tiptap <2.1.0, but I don't think it's worth the complexity/overhead of that implementation, so I'll go ahead and merge this.

Thanks again!

**Comment by sjdemartini** [comment]
(Oh and I did update the dev dependencies for mui-tiptap in https://github.com/sjdemartini/mui-tiptap/pull/312, as I mentioned I wanted to do first.)

**Comment by abaransy-business** [comment]
Thank you for the thoughtful review @sjdemartini. Happy to see that you ended up merging this.

Happy new years :)

**Pull request merged**
